### PR TITLE
Markers and visualization

### PR DESCRIPTION
**Pull request by JLiesenborgs**
We have been experimenting with markers in stella_vslam. I cleaned up the modifications we made that seem to improve their use. I've tried to be quite elaborate in the commit messages, to explain what they do.

### CODE REVIEW

**Comment by alvodo** [comment]
This can fail because the `keyframe_inserter` sets `mkr->initialized_before_ = true` but this does not add the marker to the `marker_vertex_container`. However, since the marker claims to be initialized, the `local_bundle_adjuster_g2o` wants to load from the container which is not necessarily filled yet. There is a similar problem in the global bundle adjuster and this is probably the same with the other backend as well.
I think this is a race condition as it doesnt always happen, but I have no idea about threads in C++. I do not know what the best way to fix it is.

**Comment by JLiesenborgs** [comment]
Well spotted! I'll think about how best to deal with this issue

**Comment by tvt15** [comment]
@JLiesenborgs Are you currently working on how to deal with the issue yet or were you able to solve it?

**Comment by JLiesenborgs** [comment]
I haven't had much time yet, but I do intend to look into this. Should I hurry?

**Comment by tvt15** [comment]
Im currently working on application of stella_Vslam marker integration as well. Just wanted to know more about your approach

**Comment by tvt15** [comment]
If we could connect over linkedin or email, I wanted to bounce some ideas off of you.

**Comment by JLiesenborgs** [comment]
@alvodo I apologize for taking this long, but I've finally added two commits to this pull request. The first should take care of the race condition: it records in which cases the vtx info was actually created. The second one is the small change to the 'clear' routine in map_database, as requested. 

If this looks acceptable, and you'd like to approve the pull request, it's probably best to squash the commit with the race condition fix into an earlier commit. I left it as a separate one for now for clarity, better suited for review.

@tvt15 if you check out my fork of the repository, you can find an email address you can use in the commit log

**Comment by alvodo** [comment]
@JLiesenborgs No problem, thanks for the fix! I couldnt reproduce the problem with your new version, I would therefore conclude that it is fixed. I am not a maintainer or anything of this repo, so my approval wouldnt do anything. Maybe this is a good point in time for @ymd-stella to look at it?

**Comment by JLiesenborgs** [comment]
@alvodo @ymd-stella Just a small message to notify you - I forgot to mention you a few days ago, I don't know if you get to see the update without it (apologies if you were already informed)

**Comment by tvt15** [comment]
@JLiesenborgs Hey Jori, I sent you an email regarding your work. Please do check it out when you get the time.

**Pull request merged**
